const continentMapping = {
  Algeria: "Africa",
  Angola: "Africa",
  Benin: "Africa",
  Botswana: "Africa",
  "Burkina Faso": "Africa",
  Burundi: "Africa",
  Cameroon: "Africa",
  "Cape Verde": "Africa",
  "Central African Republic": "Africa",
  Chad: "Africa",
  Comoros: "Africa",
  "Republic of Congo": "Africa",
  "Democratic Republic of the Congo": "Africa",
  Djibouti: "Africa",
  Egypt: "Africa",
  "Equatorial Guinea": "Africa",
  Eritrea: "Africa",
  Ethiopia: "Africa",
  Gabon: "Africa",
  Gambia: "Africa",
  Ghana: "Africa",
  Guinea: "Africa",
  "Guinea Bissau": "Africa",
  "Ivory Coast": "Africa",
  Kenya: "Africa",
  Lesotho: "Africa",
  "French Southern and Antarctic Lands": "Africa",
  Liberia: "Africa",
  Libya: "Africa",
  Madagascar: "Africa",
  Malawi: "Africa",
  Mali: "Africa",
  Mauritania: "Africa",
  Mauritius: "Africa",
  Morocco: "Africa",
  Mozambique: "Africa",
  Namibia: "Africa",
  Niger: "Africa",
  Nigeria: "Africa",
  Rwanda: "Africa",
  "Sao Tome and Principe": "Africa",
  Senegal: "Africa",
  Seychelles: "Africa",
  "Sierra Leone": "Africa",
  Somalia: "Africa",
  Somaliland: "Africa",
  "South Africa": "Africa",
  "South Sudan": "Africa",
  Sudan: "Africa",
  Swaziland: "Africa",
  "United Republic of Tanzania": "Africa",
  Togo: "Africa",
  Tunisia: "Africa",
  Uganda: "Africa",
  "Western Sahara": "Africa",
  Zambia: "Africa",
  Zimbabwe: "Africa",
  Afghanistan: "Asia",
  Bahrain: "Asia",
  Bangladesh: "Asia",
  Bhutan: "Asia",
  Brunei: "Asia",
  Myanmar: "Asia",
  Cambodia: "Asia",
  China: "Asia",
  "East Timor": "Asia",
  India: "Asia",
  Indonesia: "Asia",
  Iran: "Asia",
  Iraq: "Asia",
  Israel: "Asia",
  Japan: "Asia",
  Jordan: "Asia",
  Kazakhstan: "Asia",
  "North Korea": "Asia",
  "South Korea": "Asia",
  Kuwait: "Asia",
  Kyrgyzstan: "Asia",
  Laos: "Asia",
  Lebanon: "Asia",
  Malaysia: "Asia",
  Maldives: "Asia",
  Mongolia: "Asia",
  Nepal: "Asia",
  Oman: "Asia",
  Pakistan: "Asia",
  Philippines: "Asia",
  Qatar: "Asia",
  "Saudi Arabia": "Asia",
  Singapore: "Asia",
  "Sri Lanka": "Asia",
  Syria: "Asia",
  Tajikistan: "Asia",
  Thailand: "Asia",
  Turkey: "Asia",
  Turkmenistan: "Asia",
  Taiwan: "Asia",
  "United Arab Emirates": "Asia",
  Uzbekistan: "Asia",
  Vietnam: "Asia",
  Yemen: "Asia",
  Albania: "Europe",
  Andorra: "Europe",
  Armenia: "Europe",
  Austria: "Europe",
  Azerbaijan: "Europe",
  Russia: "Europe",
  Belarus: "Europe",
  Belgium: "Europe",
  "Bosnia and Herzegovina": "Europe",
  Kosovo: "Europe",
  Bulgaria: "Europe",
  Croatia: "Europe",
  Cyprus: "Europe",
  "Northern Cyprus": "Europe",
  "Czech Republic": "Europe",
  Denmark: "Europe",
  Estonia: "Europe",
  Finland: "Europe",
  France: "Europe",
  Georgia: "Europe",
  Germany: "Europe",
  Greece: "Europe",
  Hungary: "Europe",
  Iceland: "Europe",
  Ireland: "Europe",
  Italy: "Europe",
  Latvia: "Europe",
  Liechtenstein: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  Macedonia: "Europe",
  Malta: "Europe",
  Moldova: "Europe",
  Monaco: "Europe",
  Montenegro: "Europe",
  Netherlands: "Europe",
  Norway: "Europe",
  Poland: "Europe",
  Portugal: "Europe",
  Romania: "Europe",
  "San Marino": "Europe",
  "Republic of Serbia": "Europe",
  Slovakia: "Europe",
  Slovenia: "Europe",
  Spain: "Europe",
  Sweden: "Europe",
  Switzerland: "Europe",
  Ukraine: "Europe",
  "United Kingdom": "Europe",
  Vatican: "Europe",
  "Antigua and Barbuda": "NorthAmerica",
  Montserrat: "NorthAmerica",
  "The Bahamas": "NorthAmerica",
  Barbados: "NorthAmerica",
  Belize: "NorthAmerica",
  Canada: "NorthAmerica",
  "Costa Rica": "NorthAmerica",
  Cuba: "NorthAmerica",
  Dominica: "NorthAmerica",
  "Dominican Republic": "NorthAmerica",
  "El Salvador": "NorthAmerica",
  Grenada: "NorthAmerica",
  Guatemala: "NorthAmerica",
  Haiti: "NorthAmerica",
  Honduras: "NorthAmerica",
  Jamaica: "NorthAmerica",
  Mexico: "NorthAmerica",
  Nicaragua: "NorthAmerica",
  Panama: "NorthAmerica",
  "Puerto Rico": "NorthAmerica",
  "Saint Kitts and Nevis": "NorthAmerica",
  "Saint Lucia": "NorthAmerica",
  "Saint Vincent and the Grenadines": "NorthAmerica",
  "United States of America": "NorthAmerica",
  "United States Virgin Islands": "NorthAmerica",
  "British Virgin Islands": "NorthAmerica",
  "Saint Martin": "NorthAmerica",
  Anguilla: "NorthAmerica",
  "United States Minor Outlying Islands": "NorthAmerica",
  "Saint Barthelemy": "NorthAmerica",
  "Trinidad and Tobago": "NorthAmerica",
  "Sint Maarten": "NorthAmerica",
  Australia: "Australia",
  Fiji: "Australia",
  Kiribati: "Australia",
  "Marshall Islands": "Australia",
  Micronesia: "Australia",
  Nauru: "Australia",
  "New Zealand": "Australia",
  Palau: "Australia",
  "Papua New Guinea": "Australia",
  Samoa: "Australia",
  "Solomon Islands": "Australia",
  Tonga: "Australia",
  Tuvalu: "Australia",
  Vanuatu: "Australia",
  Argentina: "SouthAmerica",
  Bolivia: "SouthAmerica",
  Brazil: "SouthAmerica",
  Chile: "SouthAmerica",
  Colombia: "SouthAmerica",
  Ecuador: "SouthAmerica",
  Guyana: "SouthAmerica",
  Paraguay: "SouthAmerica",
  Peru: "SouthAmerica",
  Suriname: "SouthAmerica",
  Uruguay: "SouthAmerica",
  Venezuela: "SouthAmerica",
  Aruba: "SouthAmerica",
  Curaçao: "SouthAmerica",

  "Baykonur Cosmodrome": "Other",
  "Siachen Glacier": "Other",
};

export default continentMapping;
